services:
  - type: web
    name: loan-eligibility-api
    env: python
    plan: free  # or 'starter'/'standard' for paid plans
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host=0.0.0.0 --port=8000"
    autoDeploy: true  # Enables automatic deployment on every push
    envVars:
      - key: "ENV"
        value: "production"
      - key: "RENDER_EXTERNAL_HOSTNAME"
        sync: true  # Auto-injected by Render
